name: Test

on:
  push:
    paths:
      - '.github/workflows/test.yml'
      - '**/*.swift'
  pull_request:
    paths:
      - '.github/workflows/test.yml'
      - '**/*.swift'

jobs:
  swift-test:
    strategy:
      fail-fast: true
      matrix:
        operating-system: ["macos-12", "ubuntu-18.04", "ubuntu-20.04"]
        swift-version: ["5.6.2"]
        include:
          - swift-version: "5.6.2"
            xcode-version: "13.4.1"
    runs-on: ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v2
      - uses: sinoru/actions-setup-xcode@v2
        if: ${{ startsWith(matrix.operating-system, 'macos') && matrix.xcode-version }}
        with:
          xcode-version: ${{ matrix.xcode-version }}
          apple-id: ${{ secrets.APPLE_ID }}
          apple-id-password: ${{ secrets.APPLE_ID_PASSWORD }}
      - uses: sinoru/actions-setup-swift@v2
        with:
          swift-version: ${{ matrix.swift-version }}
      - uses: actions/cache@v3
        id: cache
        with:
          path: .build
          key: ${{ matrix.operating-system }}-swift-${{ env.SWIFT_VERSION }}-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ matrix.operating-system }}-swift-${{ env.SWIFT_VERSION }}-
            ${{ matrix.operating-system }}-swift-
      - name: Resolve Package Dependencies
        run: swift resolve
      - name: Build
        run: swift build --disable-automatic-resolution --build-tests
        env:
          SWIFT_VERSION: ${{ matrix.swift-version }}
      - name: Run tests
        run: swift test --disable-automatic-resolution --skip-build
        env:
          SWIFT_VERSION: ${{ matrix.swift-version }}
  xcode-test:
    strategy:
      fail-fast: true
      matrix:
        xcode-version: ["13.4.1"]
        xcode-destination: [
          "platform=OS X,arch=x86_64",
          "platform=OS X,arch=x86_64,variant=Mac Catalyst",
          "platform=iOS Simulator,name=iPhone 12 Pro,OS=latest",
          "platform=tvOS Simulator,name=Apple TV,OS=latest",
          "platform=watchOS Simulator,name=Apple Watch Series 6 - 44mm,OS=latest",
        ]
        include:
          - xcode-version: "13.4.1"
            operating-system: "macos-12"
    runs-on: ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v2
      - uses: sinoru/actions-setup-xcode@v2
        with:
          xcode-version: ${{ matrix.xcode-version }}
          apple-id: ${{ secrets.APPLE_ID }}
          apple-id-password: ${{ secrets.APPLE_ID_PASSWORD }}
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData
          key: ${{ matrix.operating-system }}-Xcode-${{ matrix.xcode-version }}
          restore-keys: |
            ${{ matrix.operating-system }}-Xcode-
      - name: Resolve Package Dependencies
        run: xcodebuild -resolvePackageDependencies
      - name: Analyze
        run: xcodebuild -scheme swift-discord-Package -destination '${{ matrix.xcode-destination }}' -disableAutomaticPackageResolution analyze
      - name: Test
        run: xcodebuild -scheme swift-discord-Package -destination '${{ matrix.xcode-destination }}' -disableAutomaticPackageResolution test
